apiVersion: v1
kind: Service
metadata:
  name: notification-hub
  namespace: notification
  labels:
    app.kubernetes.io/name: notification-hub
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: notification-hub
