-- 초기 스키마. Postgres / H2 (PostgreSQL mode) 모두 호환.

CREATE TABLE recipient (
    id           VARCHAR(128) PRIMARY KEY,
    channels_json VARCHAR(4000) NOT NULL,
    locale       VARCHAR(16) NOT NULL,
    timezone     VARCHAR(64) NOT NULL
);

CREATE TABLE user_preference (
    recipient_id   VARCHAR(128) PRIMARY KEY,
    allowed_json   VARCHAR(2000) NOT NULL,
    preferred_json VARCHAR(2000) NOT NULL,
    quiet_start    VARCHAR(8),
    quiet_end      VARCHAR(8),
    timezone       VARCHAR(64) NOT NULL
);

CREATE TABLE template (
    id            UUID PRIMARY KEY,
    template_key  VARCHAR(128) NOT NULL,
    locale        VARCHAR(16) NOT NULL,
    channel_type  VARCHAR(32) NOT NULL,
    title_template VARCHAR(200) NOT NULL,
    body_template  VARCHAR(4000) NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_template_key_locale_channel UNIQUE (template_key, locale, channel_type)
);
CREATE INDEX ix_template_key ON template (template_key);

CREATE TABLE device_token (
    id            UUID PRIMARY KEY,
    recipient_id  VARCHAR(128) NOT NULL,
    platform      VARCHAR(16) NOT NULL,
    token         VARCHAR(256) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    disabled_at   TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uq_device_token_value UNIQUE (token)
);
CREATE INDEX ix_device_token_recipient ON device_token (recipient_id);

CREATE TABLE notification (
    id              UUID PRIMARY KEY,
    idempotency_key VARCHAR(128) NOT NULL UNIQUE,
    recipient_id    VARCHAR(128) NOT NULL,
    kind            VARCHAR(32) NOT NULL,
    title           VARCHAR(200) NOT NULL,
    body            VARCHAR(4000) NOT NULL,
    payload_json    VARCHAR(4000) NOT NULL,
    template_key    VARCHAR(128),
    status          VARCHAR(16) NOT NULL,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_notification_recipient_created
    ON notification (recipient_id, created_at DESC);

CREATE TABLE delivery_attempt (
    id                UUID PRIMARY KEY,
    notification_id   UUID NOT NULL,
    channel_type      VARCHAR(32) NOT NULL,
    channel_address   VARCHAR(256) NOT NULL,
    rendered_title    VARCHAR(200) NOT NULL,
    rendered_body     VARCHAR(4000) NOT NULL,
    status            VARCHAR(16) NOT NULL,
    retry_count       INTEGER NOT NULL,
    next_attempt_at   TIMESTAMP WITH TIME ZONE,
    completed_at      TIMESTAMP WITH TIME ZONE,
    vendor_message_id VARCHAR(128),
    failure_reason    VARCHAR(512),
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX ix_delivery_attempt_notification ON delivery_attempt (notification_id);
CREATE INDEX ix_delivery_attempt_status_next  ON delivery_attempt (status, next_attempt_at);

CREATE TABLE outbox_event (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic        VARCHAR(128) NOT NULL,
    key_value    VARCHAR(128) NOT NULL,
    event_id     VARCHAR(64)  NOT NULL,
    event_type   VARCHAR(64)  NOT NULL,
    payload_json VARCHAR(4000) NOT NULL,
    status       VARCHAR(16)  NOT NULL,
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE
);
CREATE INDEX ix_outbox_event_status_created ON outbox_event (status, created_at);
